CREATE TABLE IF NOT EXISTS posts (
  post_id SERIAL PRIMARY KEY NOT NULL,
  post_html TEXT NOT NULL,
  tags VARCHAR[],
  user_id VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);