CREATE TABLE IF NOT EXISTS friends (
  friend_id SERIAL PRIMARY KEY NOT NULL,
	user_id_requester INTEGER NOT NULL,
	user_id_accepter INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);